#!/bin/bash

# delete partitions on sdb disks
PARTITIONS=$(ls -l  /dev/ | grep sdb | awk '{print $10}' | tail -n +2 |  sed -e 's/^sdb//')

for i in $PARTITIONS;
do mount | grep sdb | umount /dev/sdb$i > /dev/null  && parted -s /dev/sdb rm $i 
done

